- README.md
- backend/src/config/api-config.ts
- backend/yarn.lock
> Adjust API subscriptions

- frontend/src/layouts/banner-menu/banner-menu-items.tsx
- frontend/src/layouts/banner-menu/banner-menu.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/announcements/announcements.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/consumption/consumption-card.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/consumption/consumption.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/todo/todos.module.scss
- frontend/tailwind.scss
> msi-120 feature: basic overview page

- frontend/src/app/foretag/(mypages-sections)/avtal/[agreementId]/page.tsx
- frontend/src/app/foretag/(mypages-sections)/avtal/page.tsx
- frontend/src/app/privat/avtal/[agreementId]/page.tsx
- frontend/src/app/privat/avtal/page.tsx
- frontend/src/layouts/banner-menu/banner-menu-items.tsx
- frontend/src/layouts/banner-menu/banner-menu.component.tsx
- frontend/src/layouts/pages/mypages-sections/agreements.component.tsx
- frontend/src/layouts/pages/mypages-sections/agreements/agreement-list-item/agreement-list-item.component.tsx
- frontend/src/layouts/pages/mypages-sections/agreements/agreement/agreement.component.tsx
- frontend/tailwind.scss
> msi-150 Feature/msi 150 agreements tab

- frontend/src/app/foretag/(mypages-sections)/sjalvservice/page.tsx
- frontend/src/app/privat/sjalvservice/page.tsx
- frontend/src/layouts/banner-menu/banner-menu-items.tsx
- frontend/src/layouts/pages/mypages-sections/self-service/external-link-card/external-link-card.component.tsx
- frontend/src/layouts/pages/mypages-sections/self-service/self-service/self-service.component.tsx
- frontend/src/layouts/pages/mypages-sections/self-service/self-service/self-services.ts
> msi-160 feature: self-service

- frontend/src/layouts/app/login-guard.tsx
> msi-182 fix: prevent repeating redirect in login guard

- frontend/next.config.js
> Use basepath from config

- backend/src/controllers/invoices.controller.ts
- frontend/src/components/cards/cards.component.tsx
- frontend/src/components/table-wrapper/table-wrapper.component.tsx
- frontend/src/layouts/pages/mypages-sections/invoices.component.tsx
- frontend/src/layouts/pages/mypages-sections/invoices/invoices-card-entry.component.tsx
- frontend/src/layouts/pages/mypages-sections/invoices/invoices-card-list.component.tsx
- frontend/src/layouts/pages/mypages-sections/invoices/invoices-list.component.tsx
- frontend/src/layouts/pages/mypages-sections/invoices/invoices-table.component.tsx
> msi-97 feature: filter pending invoices

- backend/src/controllers/invoices.controller.ts
- frontend/src/layouts/pages/mypages-sections/invoices.component.tsx
- frontend/src/layouts/pages/mypages-sections/invoices/invoices-card-list.component.tsx
- frontend/src/layouts/pages/mypages-sections/invoices/invoices-list.component.tsx
- frontend/src/layouts/pages/mypages-sections/invoices/invoices-table.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/todo/todo-list-item.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/todo/todos.component.tsx
> msi-183 feature: todo section

- frontend/src/components/logotypes/logotypes.component.tsx
- frontend/src/layouts/default-layout.component.tsx
- frontend/src/layouts/layout.component.tsx
> msi-155 feature: logotype component

- frontend/src/layouts/pages/login.component.tsx
- frontend/src/layouts/pages/valj-foretag/valj-foretag.component.tsx
> msi-185 feature: logged out landing state and updated styling for login

- frontend/src/interfaces/agreement.ts
- frontend/src/layouts/pages/mypages-sections/agreements.component.tsx
> Some adjustments

- backend/src/controllers/agreement.controller.ts
> fix: using correct party id

- frontend/src/layouts/pages/mypages-sections/overview/todo/todo-list-item.component.tsx
> msi-198 fix: responsive design adjustments

- backend/src/controllers/user.controller.ts
- backend/src/types/express-session.d.ts
- frontend/package.json
- frontend/src/components/logotypes/logotypes.component.tsx
- frontend/src/layouts/default-layout.component.tsx
- frontend/src/layouts/layout.component.tsx
- frontend/src/layouts/pages/om-webbplatsen/kakor.component.tsx
- frontend/src/layouts/pages/om-webbplatsen/tillganglighet.component.tsx
Toggle logotypes in header based on customer relations. Adjust footer, a11y and cookies pages. Fix caching in user controller and add dedicated endpoint for fetching relations to make it quicker.
> MSI-191 Toggle logotypes in header based on customer relations.

- frontend/src/layouts/pages/login.component.tsx
> msi-207 fix: Removed unnecessary text block and added additional info for logget out state

- frontend/src/layouts/app/layout.component.tsx
- frontend/src/layouts/banner-menu/banner-menu.component.tsx
- frontend/src/layouts/entry-layout.component.tsx
- frontend/tailwind.config.js
[UF-16310](https://jira.sundsvall.se/browse/UF-16310)
> feat: added new colors to page header

- frontend/src/layouts/pages/mypages-sections/statistics.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/charts/charts.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/charts/electricity-consumption/consumption-information.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/charts/electricity-consumption/electricity-consumption.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/charts/outdoor-temperature/outdoor-temperature.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/export-statistics-button/export-statistics-button.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/faq/faq.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/statistics-filter.component.tsx
https://jira.sundsvall.se/browse/MSI-211 och https://jira.sundsvall.se/browse/MSI-208
> msi-211 feat: statistics page base layout

- backend/src/controllers/user.controller.ts
- frontend/src/layouts/pages/mypages-sections/agreements/agreement/agreement.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/consumption/consumption.component.tsx
- frontend/src/services/measurement-data-service.ts
> fix: label production facilities

- frontend/src/interfaces/announcements.ts
- frontend/src/layouts/pages/mypages-sections/overview/announcements/announcements.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/consumption/consumption.component.tsx
- frontend/src/utils/app-organizations.ts
> msi-206 feat: only display announcements relevant to user

- frontend/package.json
- frontend/src/layouts/pages/mypages-sections/statistics.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/charts/charts.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/export-statistics-button/export-statistics-button.component.tsx
- frontend/yarn.lock
https://jira.sundsvall.se/browse/MSI-210
> msi-210 feat: export of statistics data

- frontend/src/layouts/pages/om-webbplatsen/index.component.tsx
https://jira.sundsvall.se/browse/MSI-240
> msi-240 feature: about page

- frontend/src/layouts/layout.component.tsx
- frontend/tailwind.scss
https://jira.sundsvall.se/browse/MSI-245
> msi-245 fix: cookie banner title and button colors

- frontend/src/components/form/connect-form.component.tsx
- frontend/src/components/form/form-box.component.tsx
- frontend/src/layouts/pages/mypages-sections/profile/components/delegate-filter.component.tsx
- frontend/src/layouts/pages/mypages-sections/profile/components/delegate-item.component.tsx
- frontend/src/layouts/pages/mypages-sections/profile/profile-contact-details.component.tsx
- frontend/src/layouts/pages/mypages-sections/profile/profile-contact-settings.component.tsx
- frontend/src/layouts/pages/mypages-sections/profile/profile-delegate-details.component.tsx
- frontend/src/layouts/pages/mypages-sections/profile/profile.component.tsx
https://jira.sundsvall.se/browse/MSI-227
> msi-227 feat: contact settings design

- frontend/src/layouts/pages/mypages-sections/statistics/charts/consumption/consumption-chart/consumption-chart.component.tsx
https://jira.sundsvall.se/browse/MSI-236
> msi-236 fix: dynamic y-axis domain

- frontend/src/layouts/pages/mypages-sections/overview/consumption/consumption-card.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/consumption/consumption.component.tsx
- frontend/src/services/measurement-data-service.ts
> Make date a property. Use dayjs for date calculations. Handle 0 diff.

- frontend/src/layouts/pages/mypages-sections/agreements/agreement/agreement.component.tsx
https://jira.sundsvall.se/browse/MSI-252
> msi-252 fix: additional agreements and inactive agreement label

- frontend/src/app/foretag/(mypages-sections)/layout.tsx
- frontend/src/app/privat/layout.tsx
- frontend/src/contexts/app.context.tsx
- frontend/src/layouts/banner-menu/banner-menu.component.tsx
- frontend/src/layouts/pages/mypages-sections/invoices/invoices-card-list.component.tsx
- frontend/src/layouts/pages/mypages-sections/invoices/invoices-table.component.tsx
- frontend/src/layouts/site-menu/site-menu-items.tsx
- frontend/src/utils/to-representing-label.ts
> msi-189 fix: refresh invoices on representation change

- backend/src/controllers/user.controller.ts
- frontend/src/layouts/app/login-guard.tsx
- frontend/src/layouts/pages/valj-foretag/valj-foretag.component.tsx
https://jira.sundsvall.se/browse/MSI-259
> Undefined check and delay for redirect

- frontend/src/layouts/pages/mypages-sections/agreements/agreement/agreement.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/consumption/consumption.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/todo/todos.component.tsx
- frontend/src/layouts/pages/mypages-sections/self-service/self-service/self-service.component.tsx
> Undefined checks

- frontend/src/layouts/pages/mypages-sections/invoices.component.tsx
- frontend/src/layouts/pages/mypages-sections/overview/consumption/consumption.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/statistics-filter/statistics-filter.component.tsx
> More undefined checks

- frontend/src/layouts/pages/mypages-sections/profile/components/delegate-filter.component.tsx
- frontend/src/layouts/pages/mypages-sections/profile/components/delegate-item.component.tsx
> Filter delegate settings based on user facilities

- frontend/src/layouts/banner-menu/banner-menu.component.tsx
- frontend/src/layouts/pages/login.component.tsx
- frontend/src/utils/title-caser.ts
Jira https://jira.sundsvall.se/browse/MSI-263
> Make name title case

- .github/CODEOWNERS
> fix: Add CODEOWNERS file for github workflows

- frontend/src/layouts/pages/mypages-sections/statistics/statistics-filter/statistics-filter.component.tsx
https://jira.sundsvall.se/browse/UF-17171
> uf-17171 fix: reverse facility type list

- frontend/src/components/contact-settings-confirmation/contact-settings-confirmation.component.tsx
> uf-17229 fix: handling of cookie banner and onboarding modal

- frontend/src/layouts/pages/mypages-sections/statistics.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/statistics-filter/components/statistics-filter-day.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/statistics-filter/components/statistics-filter-month.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/statistics-filter/components/statistics-filter-year.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/statistics-filter/statistics-filter.component.tsx
[UF-17225](https://jira.sundsvall.se/browse/UF-17225)
> fix: remeber dates on tab change

- frontend/src/interfaces/measurement-data.ts
- frontend/src/layouts/pages/mypages-sections/statistics/charts/charts.component.tsx
- frontend/src/layouts/pages/mypages-sections/statistics/charts/consumption/consumption-chart/consumption-chart.component.tsx
- frontend/src/services/measurement-data-service.ts
[UF-17246](https://jira.sundsvall.se/browse/UF-17246)
[UF-17247](https://jira.sundsvall.se/browse/UF-17247)
[UF-17248](https://jira.sundsvall.se/browse/UF-17248)
> fix: merge data by date

- frontend/src/app/foretag/(mypages-sections)/avtal/[...slug]/page.tsx
- frontend/src/app/privat/avtal/[...slug]/page.tsx
- frontend/src/layouts/pages/mypages-sections/agreements/agreement/agreement.component.tsx
https://jira.sundsvall.se/browse/UF-17303
> uf-17303 fix: use params for agreement

- frontend/src/app/foretag/(mypages-sections)/avtal/[...slug]/page.tsx
- frontend/src/app/foretag/(mypages-sections)/avtal/page.tsx
- frontend/src/app/foretag/(mypages-sections)/fakturor/page.tsx
- frontend/src/app/foretag/(mypages-sections)/oversikt/page.tsx
- frontend/src/app/foretag/(mypages-sections)/profil/page.tsx
- frontend/src/app/foretag/(mypages-sections)/sjalvservice/page.tsx
- frontend/src/app/foretag/(mypages-sections)/statistik/page.tsx
- frontend/src/app/foretag/valj-foretag/page.tsx
- frontend/src/layouts/pages/valj-foretag/no-represent.tsx
- frontend/src/layouts/site-menu/site-menu-items.tsx
https://jira.sundsvall.se/browse/MSI-335
> msi-335 fix: updated site menu and page titles

- backend/src/services/contact-setting.service.ts
Sätt korrekt defaultvärde för alias i ContactSetting
Jira https://jira.sundsvall.se/browse/MSI-352
> fix: set alias to 'default' instead of null for new contact settings

- frontend/src/interfaces/measurement-data.ts
- frontend/src/layouts/pages/mypages-sections/statistics/charts/charts.component.tsx
- frontend/src/services/measurement-data-service.ts
> msi-353 fix: merged temperature data
